### PR TITLE
Port to Seeed XIAO RP2040

### PR DESCRIPTION
**Pull request by deadmoo83**
Added port to Seeed XIAO RP2040 that uses Adafruit TinyUSB.

Need to install the Seeed XIAO RP2040 board and select the Adafruit TinyUSB stack to build.

### CODE REVIEW

**Comment by mikeneiderhauser** [comment]
Any specific reason why you went with a different USB core / lib?

**Comment by deadmoo83** [comment]
I just couldn't get the existing code to compile against the Seeed XIAO
RP2040 board. So I had to find an alternative that would compile against
that board.

**Comment by mikeneiderhauser** [comment]
I ordered the same Seeed XIAO board from amazon.  I'll give it a go here when it gets here. I think you can use the generic PiPico target like I'm using for the Tiny2040 board.

If I can get this new board to work, I'll whip up a PCB for it as well

**Comment by mikeneiderhauser** [comment]
Got it working with a minor code change and don't need to change the USB HID driver :-)

at the top
```
//UART Serial2(4, 5, NC, NC);  // GPIO 4/5. (Pi Pico physical pin 6/7). Also works with Tiny2040 board
UART Serial2(0, 1, NC, NC);  // SEEED XIAO RP2040 board 
```

Then wired to the back 2 pins on the module.  Looks like ill be making a board! 

I may also consider making a board for the waveshare zero module.  Has the same IO exposed as the pico/tiny2040 so shouldnt require any code changes.

I'll make some board selection bits with defines to make it easier for end users

**Comment by deadmoo83** [comment]
Awesome

**Comment by mikeneiderhauser** [comment]
@deadmoo83 I didn't forget about this.  I'll be working on a board for the XIAO in the coming days.  Keep an eye out for an upload to the repo.  Going to close this PR, as we have a different solution that doesn't require different libs.

**Comment by deadmoo83** [comment]
Sounds good, thanks!

**Comment by mikeneiderhauser** [comment]
Added a board for you. I didn't mfg it, but it should work :-)

**Comment by deadmoo83** [comment]
Awesome, thanks!

**Comment by mikeneiderhauser** [comment]
Technically the pi pico didn't require it either.  Its safe to use with the level shifter, but the ESP on the RXs are 3.3v TTL that just so happen can also take 5V TTL (in practice, but not design).  Removing the level shifter decreases the bom, makes it so we can run it flatter, and makes assembly much easier.. I've been running 2 pieces of wire on the existing pi pico boards w/o issue

**Comment by phobos-** [comment]
@mikeneiderhauser Thanks, for the confirmation, I tried it and it works fine!
IMG_20220519_190826

**Comment by mikeneiderhauser** [comment]
Carrier boards for the waveshare came in.  Hoping to test it out this weekend
20220519_221450623_iOS

**Pull request closed without merging**
